### ISSUE TITLE
vivid package missing in nightly ppa

### ISSUE THREAD

**Issue by yohanboniface** [mapnik/debian#15]
vivid seems to be missing in the nightly ppa.
Is it just about adding it in the [nightly-build.sh script](https://github.com/mapnik/debian/blob/master/nightly-build.sh#L47)?

**Comment by springmeyer** [comment]
Yes, hopefully https://github.com/mapnik/debian/commit/7c83d37f6e075e96743a38b11ed461e4d8d1913a will do it.

**Comment by yohanboniface** [comment]
Confirmed, thanks! :)
