### ISSUE TITLE
Add Mapnik v3.0 release PPA

### ISSUE THREAD

**Issue by pnorman** [mapnik/debian#17]
The previous PPAs were
Mapnik v2.0.1 release
Mapnik v2.0.2 release
Mapnik v2.1.0 release
Mapnik v2.2.0 release

Since all Mapnik 3.0.x releases should have a compatible API, would it be better to just have a Mapnik v3.0 PPA?

**Comment by pnorman** [comment]
I checked, and I don't have access to do this.

**Comment by tomhughes** [comment]
I single PPA for 3.0.x that gets new stable versions automatically would certainly be my preference.

**Comment by pnorman** [comment]
@rcoup ping on this - any way to help you with it?

**Comment by gravitystorm** [comment]
It woudl be great to know what the plan is for this - is it worth waiting for packages from here, or should we compile / make our own 3.0.x packages to use on the osmf tileservers? I don't mind waiting (or helping) but if it's never going to happen that would be worth knowing too :-)

**Comment by pnorman** [comment]
debiangis has got 3.0.9 in testing, and I understand from osgeo live that it cleanly ports over to Ubuntu.

Their packaging doesn't really replace the need for action here, but might solve the OSMF needs. And the debiangis packaging is normally quite well done.

The need for packaging **here** is so that you can have builds of the active releases (i.e. 3.0.x and 3.1.x in the future), nightly builds of the branches (3.0 dev, and again 3.1 dev when it comes out)

cc @sebastic

**Comment by sebastic** [comment]
If you need Debian packaging for Mapnik 3.0.x you can use the source package maintained by the Debian GIS team ([git](https://anonscm.debian.org/cgit/pkg-grass/mapnik.git)), no change rebuilds of the latest version in unstable should suffice for osmf tileservers. If you need changes to support older Ubuntu releases as used for the OSM infrastructure you can make those on dedicated osmf/ branches. Or consider bundling the effort with UbuntuGIS and maintain mapnik backports for Ubuntu LTS.

**Comment by pnorman** [comment]
Closing as wontfix, since PPA efforts are abandoned and no one can take over the work.

**Comment by gravitystorm** [comment]
It's a shame that nobody has either given @pnorman the access that he needs, nor explained what alternative solutions/help can be provided, nor made it obvious that the PPA has been abandoned. Any of these would have been useful, especially in a more timely manner.

**Comment by rcoup** [comment]
Hey guys,

Mostly me dropping the ball (and I've been travelling for the last few weeks). AFAIK @pnorman has had access to Launchpad since 2014 (though AFAICT it was deactivated by himself a few days ago).

I'm happy to provide code, access, or advice to help anyone, but I've struggled with time to sit down and actually work on it recently.

**Comment by pnorman** [comment]
> Mostly me dropping the ball (and I've been travelling for the last few weeks). AFAIK @pnorman has had access to Launchpad since 2014 (though AFAICT it was deactivated by himself a few days ago).

I had access to upload to PPAs, but not create new ones. I left the Mapnik Developers launchpad group because the PPA was abandoned.
